repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6 # Usa la versión más reciente de Ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
