services:
  api:
    environment:
      - DJANGO_ENV=local
      - DJANGO_SETTINGS_MODULE=core.settings.local
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:4000
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
      # - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fairsplit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_ENV=test
      - DJANGO_SETTINGS_MODULE=core.settings.test
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  # redis_data:
