[tool.ruff]
# Reglas a activar
select = [
  "E", # pycodestyle
  "F", # pyflakes
  "I", # isort
]

# Ignorar archivos/directorios específicos
exclude = [".git", ".venv", "migrations"]

# Arreglar automáticamente
fix = true

# Configuración de línea máxima
line-length = 80

[tool.ruff.lint.per-file-ignores]
"core/settings.py" = ["E501"]
