# Generated by Django 5.1.2 on 2025-02-16 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmember',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='income_currency',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='income_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-weekly', 'Bi-weekly'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Couple', 'Couple'), ('Family', 'Couple'), ('Friends', 'Couple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=50),
        ),
    ]
