# Generated by Django 5.1.2 on 2025-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_groupmember_created_at_groupmember_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom percentage for expense splitting', max_digits=5, null=True),
        ),
    ]
